<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article[
<!ELEMENT article (informaltable,para)>
<!ATTLIST article
  xmlns CDATA #FIXED ''
  lang CDATA #REQUIRED>

<!ELEMENT informaltable (tgroup)>
<!ATTLIST informaltable
  xmlns CDATA #FIXED ''
  frame NMTOKEN #REQUIRED>

<!ELEMENT tgroup (tbody)>
<!ATTLIST tgroup
  xmlns CDATA #FIXED ''
  cols CDATA #REQUIRED>

<!ELEMENT tbody (row)+>
<!ATTLIST tbody
  xmlns CDATA #FIXED ''>

<!ELEMENT row (entry)+>
<!ATTLIST row
  xmlns CDATA #FIXED ''>

<!ELEMENT entry (para)+>
<!ATTLIST entry
  xmlns CDATA #FIXED ''>

<!ELEMENT para (#PCDATA)>
<!ATTLIST para
  xmlns CDATA #FIXED ''>
]>

<article lang="">
  <informaltable frame="all">
    <tgroup cols="4">
    <tbody>
    <row>
    <entry>
    <para>Id</para>
      </entry>
    
    <entry>
    <para>Name</para>
    </entry>
    
    <entry>
    <para>Available Sizes</para>
    </entry>
    
    <entry>
    <para>Price</para>
    </entry>
    </row>
    
    <row>
    <entry>
    <para>a332d8d2-86d7-11ec-a8a3-0242ac120002</para>
    </entry>
    <entry>
    <para>Microfleece hoodie</para>
    
    </entry>
    <entry>
    <para>XS - 0 items</para>
    <para>S - 3 items</para>
    <para>M - 13 items</para>
    <para>L - 5 items</para>
    <para>XL - 2 items</para>
    <para/></entry>
    
    <entry>
    <para>USD$49.99</para>
    <para>CAD$59.99</para>
    </entry></row><row>
    <entry>
    
    <para>a332dac6-86d7-11ec-a8a3-0242ac120002</para>
    </entry>
    <entry>
    <para>Vintage Soft Hoodie</para>
    </entry>
    <entry>
    <para>XS - 3 items</para>
    <para>S - 8 items</para>
    <para>M - 25 items</para>
    <para>L - 12 items</para>
    <para>XL - 4 items</para>
    
    </entry>
    
    <entry>
    <para>USD$39.99</para>
    <para>CAD$49.99</para>
    </entry>
    </row>
    <row>
    
    <entry>
    <para>a332dbf2-86d7-11ec-a8a3-0242ac120002</para>
    </entry><entry><para>Crewneck Sweatshirt</para>
    </entry><entry><para>XS - 0 items</para>
    <para>S - 0 items</para><para>M - 15 items</para>
    <para>L - 13 items</para><para>XL - 0 items</para>
    </entry><entry><para>CAD$47.97</para>
    </entry>
    </row>
    
    <row>
    <entry>
    <para>a332dd0a-86d7-11ec-a8a3-0242ac120002</para>
    </entry>
    <entry
    ><para>French Terry Raglan Crewneck Sweatshirt</para>
    </entry>
    
    <entry>
    <para>XS - 0 items</para>
    <para>S - 0 items</para>
    <para>M - 0 items</para>
    <para>L - 1 item</para>
    <para>XL - 0 items</para>
    </entry>
    
    <entry>
    <para>USD$37.97</para>
    </entry>
    </row>
    </tbody>
    </tgroup>
  </informaltable>
  <para/>
</article>